theme: jekyll-theme-minimal
title: Octocat's homepage
description: TIL 학습법을 위한 공부 블로그
excerpt: "GitHub Pages 블로그를 검색 엔진에 노출"

categories:
  - GitHub Pages
tags:
  - GitHub Pages
  - Google Search Console
  - search engine
last_modified_at: 2022-01-25T20:30:00+09:00
sitemap:
  changefreq: daily
  priority: 0.8
